"""Generate committed scaffold env assets from env_spec.py."""

from __future__ import annotations

import importlib.util
import json
import sys
import textwrap
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    import types


def _load_env_spec() -> types.ModuleType:
    """Load env_spec.py by filesystem path (works before Copier resolves package name)."""
    src_dir = Path(__file__).resolve().parent.parent.parent / "src"
    candidates = [p for p in src_dir.iterdir() if p.is_dir() and (p / "config" / "env_spec.py").exists()]
    if not candidates:
        print("ERROR: Could not find config/env_spec.py under src/", file=sys.stderr)
        sys.exit(1)

    spec_file = candidates[0] / "config" / "env_spec.py"
    spec = importlib.util.spec_from_file_location("env_spec", spec_file)
    assert spec is not None, f"Failed to create ModuleSpec from {spec_file}"
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    assert spec.loader is not None, f"ModuleSpec for {spec_file} has no loader"
    spec.loader.exec_module(module)
    return module


def _repo_root() -> Path:
    """Return the generated project's repository root."""
    return Path(__file__).resolve().parent.parent.parent


def _render_env_example(env_spec_module: types.ModuleType) -> str:
    """Render .env.example from the offline defaults in env_spec.py."""
    mode = env_spec_module.Mode.OFFLINE  # type: ignore[attr-defined]
    lines = [
        f"# {env_spec_module.__dict__.get('__project_name__', '{{ project_name }}')} — Environment Variables",
        "# Copy to .env and fill in values for local development.",
        "# Generated from src/{{ project_slug }}/config/env_spec.py.",
        "# Generated by scripts/env/generate_env_templates.py.",
        "# See docs/reference/ENV_VARS.md for documentation.",
        "",
    ]

    current_category = None
    for var in env_spec_module.ENV_SPEC:  # type: ignore[attr-defined]
        if var.category != current_category:
            current_category = var.category
            lines.extend(
                [
                    f"# [{current_category.value}]",
                ]
            )
        wrapped = textwrap.wrap(var.description, width=88) or [var.description]
        lines.extend(f"# {line}" for line in wrapped)
        lines.append(f"{var.name}={var.defaults.get(mode, '')}")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def _render_mode_defaults(env_spec_module: types.ModuleType) -> str:
    """Render scripts/env/mode_defaults.json from env_spec.py."""
    payload = {
        "_comment": "Auto-generated - do not edit. Run scripts/env/generate_env_templates.py to regenerate.",
        "offline": env_spec_module.get_defaults_for_mode(env_spec_module.Mode.OFFLINE),  # type: ignore[attr-defined]
        "local-live": env_spec_module.get_defaults_for_mode(env_spec_module.Mode.LOCAL_LIVE),  # type: ignore[attr-defined]
        "prod": env_spec_module.get_defaults_for_mode(env_spec_module.Mode.PROD),  # type: ignore[attr-defined]
    }
    return json.dumps(payload, indent=2) + "\n"


def main() -> None:
    """Generate environment template files from env_spec.py."""
    env_spec_module = _load_env_spec()
    env_spec = env_spec_module.ENV_SPEC  # type: ignore[attr-defined]
    repo_root = _repo_root()
    env_example_path = repo_root / ".env.example"
    mode_defaults_path = repo_root / "scripts" / "env" / "mode_defaults.json"

    env_example_path.write_text(_render_env_example(env_spec_module), encoding="utf-8")
    mode_defaults_path.write_text(_render_mode_defaults(env_spec_module), encoding="utf-8")

    print(f"Found {len(env_spec)} environment variables in spec.")
    print(f"Wrote {env_example_path}")
    print(f"Wrote {mode_defaults_path}")


if __name__ == "__main__":
    main()
