#Requires -Version 7.0
<#
.SYNOPSIS
    Open the last Playwright HTML report in a browser.
.DESCRIPTION
    Serves the HTML report generated by the most recent test run.
    Run this after 'pwsh scripts/e2e-test.ps1' to view results.
.EXAMPLE
    pwsh scripts/e2e-report.ps1
#>

$ErrorActionPreference = "Stop"
$RepoRoot = Split-Path -Parent $PSScriptRoot
$E2EDir = Join-Path $RepoRoot "apps" "web" "e2e"

Push-Location $E2EDir
try {
    npx playwright show-report
    exit $LASTEXITCODE
} finally {
    Pop-Location
}
